In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7236, 5683, 4665, 2221],
 [7236, 5683, 4665, 326],
 [7236, 8187, 4665, 8633],
 [6684, 3591, 9809, 2087, 4821],
 [6684, 3591, 9809, 2087, 2047],
 [8894, 7236, 674, 4665, 2205],
 [1758, 1116, 1169, 2087]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7236 5683 4665 2221]
 [   0    0    0    0 7236 5683 4665  326]
 [   0    0    0    0 7236 8187 4665 8633]
 [   0    0    0 6684 3591 9809 2087 4821]
 [   0    0    0 6684 3591 9809 2087 2047]
 [   0    0    0 8894 7236  674 4665 2205]
 [   0    0    0    0 1758 1116 1169 2087]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 102ms/step


array([[[ 0.00791083, -0.00697086,  0.02002848,  0.03052696,
          0.04393495,  0.00451429,  0.04737583, -0.01562815,
          0.01127837,  0.01860929],
        [ 0.00791083, -0.00697086,  0.02002848,  0.03052696,
          0.04393495,  0.00451429,  0.04737583, -0.01562815,
          0.01127837,  0.01860929],
        [ 0.00791083, -0.00697086,  0.02002848,  0.03052696,
          0.04393495,  0.00451429,  0.04737583, -0.01562815,
          0.01127837,  0.01860929],
        [ 0.00791083, -0.00697086,  0.02002848,  0.03052696,
          0.04393495,  0.00451429,  0.04737583, -0.01562815,
          0.01127837,  0.01860929],
        [-0.00709707, -0.02160749, -0.01328604, -0.0354116 ,
          0.0411833 ,  0.02501024, -0.02917006, -0.03701671,
          0.03050783,  0.01103478],
        [-0.0444734 , -0.03027276,  0.01379908, -0.01156557,
          0.03002249, -0.02907056,  0.0111009 ,  0.01377393,
         -0.01820147, -0.01879292],
        [-0.01683171, -0.00857211,  0.00996269,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 7236, 5683, 4665, 2221])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 48ms/step


array([[ 0.00791083, -0.00697086,  0.02002848,  0.03052696,  0.04393495,
         0.00451429,  0.04737583, -0.01562815,  0.01127837,  0.01860929],
       [ 0.00791083, -0.00697086,  0.02002848,  0.03052696,  0.04393495,
         0.00451429,  0.04737583, -0.01562815,  0.01127837,  0.01860929],
       [ 0.00791083, -0.00697086,  0.02002848,  0.03052696,  0.04393495,
         0.00451429,  0.04737583, -0.01562815,  0.01127837,  0.01860929],
       [ 0.00791083, -0.00697086,  0.02002848,  0.03052696,  0.04393495,
         0.00451429,  0.04737583, -0.01562815,  0.01127837,  0.01860929],
       [-0.00709707, -0.02160749, -0.01328604, -0.0354116 ,  0.0411833 ,
         0.02501024, -0.02917006, -0.03701671,  0.03050783,  0.01103478],
       [-0.0444734 , -0.03027276,  0.01379908, -0.01156557,  0.03002249,
        -0.02907056,  0.0111009 ,  0.01377393, -0.01820147, -0.01879292],
       [-0.01683171, -0.00857211,  0.00996269,  0.02323807, -0.02779198,
        -0.01619171,  0.01869197, -0.02654215